version: '3.9'
services:
  guitar_shop_postgres:
    image: postgres:14-alpine
    container_name: guitar_shop_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - guitar_shop_postgres:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - guitar_shop

  guitar_shop_pgadmin:
    image: dpage/pgadmin4
    container_name: guitar_shop_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - guitar_shop_postgres
    networks:
      - guitar_shop
  
  guitar_shop_fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: guitar_shop_fakesmtp
    hostname: guitar_shop_fakesmtp
    ports:
      - ${FAKE_SMTP_SERVER_PORT_1}:8025
      - ${FAKE_SMTP_SERVER_PORT_2}:8080

volumes:
  guitar_shop_postgres:

networks:
  guitar_shop:
      driver: bridge
