# Get all guitars
GET http://localhost:3001/api/guitars HTTP/1.1

###

# Create a new guitar
POST http://localhost:3001/api/guitars HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA0NzgyLCJleHAiOjE3MDc4MDUwODJ9.nDVQuO2380falQOdhh6JTFanm8smN8WT7hTBoAFTJg4

{
  "title": "New guitar 1",
  "description": "New guitar description 1",
  "photo": "photo 1",
  "type": "аккустика",
  "vendorCode": "sdpifjngfddfgd",
  "guitarStrings": 2,
  "price": 1
}

###

# Update guitar by id
PATCH http://localhost:3001/api/guitars/24f609ca-4806-4266-8a9b-15931b8a2597 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA0NzgyLCJleHAiOjE3MDc4MDUwODJ9.nDVQuO2380falQOdhh6JTFanm8smN8WT7hTBoAFTJg4
Content-Type: application/json

{
  "title": "Updated guitar title 1",
  "vendorCode": "updated vendor code 1",
  "guitarStrings": 20,
  "price": 100
}

###
