# Get all guitars
GET http://localhost:3001/api/guitars HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA4OTA5LCJleHAiOjE3MDc4MDkyMDl9.zFi-i8EgFs28bIh2UgeVWIFgvWzLfGdyyG4kXcKjJzU

###

# Create a new guitar
POST http://localhost:3001/api/guitars HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNGQ2MzE1LTIzODgtNDBjYS05ZDBhLTJmMDE1ZDIzMTVhYyIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AbG9jYWwubG9jYWwiLCJpYXQiOjE3MDc4MTExMjcsImV4cCI6MTcwODExMTEyN30._U3gQYUCT2SD0LnBmLv-MwL6mdKEt_O2h_jxQay8EDc

--boundary
Content-Disposition: form-data; name="file"; filename="catalog-product-0@2x.png"
Content-Type: image/png

< ../../../../frontend/public/img/content/catalog-product-0@2x.png

--boundary
Content-Disposition: form-data; name="title"

New guitar 1
--boundary
Content-Disposition: form-data; name="description"

New guitar description 1
--boundary
Content-Disposition: form-data; name="type"

аккустика
--boundary
Content-Disposition: form-data; name="vendorCode"

sdpifjngfddfgd
--boundary
Content-Disposition: form-data; name="guitarStrings"

4
--boundary
Content-Disposition: form-data; name="price"

301
--boundary--

###

# Get guitar by id
GET http://localhost:3001/api/guitars/030dc74b-b7d9-40e9-9249-4d01e3bddade HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNGQ2MzE1LTIzODgtNDBjYS05ZDBhLTJmMDE1ZDIzMTVhYyIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AbG9jYWwubG9jYWwiLCJpYXQiOjE3MDc4MTExMjcsImV4cCI6MTcwODExMTEyN30._U3gQYUCT2SD0LnBmLv-MwL6mdKEt_O2h_jxQay8EDc

###

# Get guitar photo file
GET http://localhost:3001/api/guitars/f7614fc4-f790-40bd-9d6f-8e0a14a7de63/photo HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNGQ2MzE1LTIzODgtNDBjYS05ZDBhLTJmMDE1ZDIzMTVhYyIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AbG9jYWwubG9jYWwiLCJpYXQiOjE3MDc4MTExMjcsImV4cCI6MTcwODExMTEyN30._U3gQYUCT2SD0LnBmLv-MwL6mdKEt_O2h_jxQay8EDc

###

# Update guitar by id
PATCH http://localhost:3001/api/guitars/030dc74b-b7d9-40e9-9249-4d01e3bddade HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJiNGQ2MzE1LTIzODgtNDBjYS05ZDBhLTJmMDE1ZDIzMTVhYyIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AbG9jYWwubG9jYWwiLCJpYXQiOjE3MDc4MTExMjcsImV4cCI6MTcwODExMTEyN30._U3gQYUCT2SD0LnBmLv-MwL6mdKEt_O2h_jxQay8EDc
Content-Type: application/json

{
  "title": "Updated guitar title 1",
  "vendorCode": "updated vendor code 1",
  "guitarStrings": 6,
  "price": 100
}

###

# Delete the post by id
DELETE http://localhost:3001/api/guitars/030dc74b-b7d9-40e9-9249-4d01e3bddade HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA1MTEzLCJleHAiOjE3MDc4MDU0MTN9.1Gxbkh0ja_uPU3nfSs12YbmcTfh5hCNg7tfequLGfAk

###
