# Get all guitars
GET http://localhost:3001/api/guitars HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA4OTA5LCJleHAiOjE3MDc4MDkyMDl9.zFi-i8EgFs28bIh2UgeVWIFgvWzLfGdyyG4kXcKjJzU

###

# Create a new guitar
POST http://localhost:3001/api/guitars HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA4OTA5LCJleHAiOjE3MDc4MDkyMDl9.zFi-i8EgFs28bIh2UgeVWIFgvWzLfGdyyG4kXcKjJzU

{
  "title": "New guitar 1",
  "description": "New guitar description 1",
  "photo": "photo 1",
  "type": "аккустика",
  "vendorCode": "sdpifjngfddfgd",
  "guitarStrings": 2,
  "price": 1
}

###

# Get guitar by id
GET http://localhost:3001/api/guitars/030dc74b-b7d9-40e9-9249-4d01e3bddade HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA4OTA5LCJleHAiOjE3MDc4MDkyMDl9.zFi-i8EgFs28bIh2UgeVWIFgvWzLfGdyyG4kXcKjJzU

###

# Update guitar by id
PATCH http://localhost:3001/api/guitars/030dc74b-b7d9-40e9-9249-4d01e3bddade HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA4OTA5LCJleHAiOjE3MDc4MDkyMDl9.zFi-i8EgFs28bIh2UgeVWIFgvWzLfGdyyG4kXcKjJzU
Content-Type: application/json

{
  "title": "Updated guitar title 1",
  "vendorCode": "updated vendor code 1",
  "guitarStrings": 20,
  "price": 100
}

###

# Delete the post by id
DELETE http://localhost:3001/api/guitars/030dc74b-b7d9-40e9-9249-4d01e3bddade HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjNlMTJkNGRhLTdjZTctNGY2Ny1iODk0LWFjOTk3NTY1MjdhMiIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW41QGxvY2FsLmxvY2FsIiwiaWF0IjoxNzA3ODA1MTEzLCJleHAiOjE3MDc4MDU0MTN9.1Gxbkh0ja_uPU3nfSs12YbmcTfh5hCNg7tfequLGfAk

###
